import { KanbanColumn } from './types';

export const kanbanColumns: KanbanColumn[] = [
  {
    id: 'quoted',
    title: 'Quoted',
    color: '#2563eb',
    cards: [
      {
        id: 'WIQ-101',
        name: 'Tesla Model 3 Full Wrap',
        vehicle: '2024 Tesla Model 3 — Satin Black',
        client: 'AutoLux Motors',
        value: 4200,
        date: '2026-03-15',
        priority: 'high',
        tags: ['full-wrap', 'rush'],
        team: [
          { initials: 'JD', color: '#2563eb' },
          { initials: 'KR', color: '#7c3aed' },
        ],
      },
      {
        id: 'WIQ-102',
        name: 'Sprinter Van Commercial Wrap',
        vehicle: '2025 Mercedes Sprinter — White Base',
        client: 'QuickServ Plumbing',
        value: 6800,
        date: '2026-03-18',
        priority: 'medium',
        tags: ['full-wrap', 'commercial'],
        team: [{ initials: 'AM', color: '#059669' }],
      },
    ],
  },
  {
    id: 'confirmed',
    title: 'Confirmed',
    color: '#7c3aed',
    cards: [
      {
        id: 'WIQ-098',
        name: 'BMW M4 Color Change',
        vehicle: '2024 BMW M4 — Gloss Racing Green',
        client: 'James Morton',
        value: 5500,
        date: '2026-03-12',
        priority: 'high',
        tags: ['full-wrap'],
        team: [
          { initials: 'KR', color: '#7c3aed' },
          { initials: 'LN', color: '#e11d48' },
        ],
        tasks: [
          { label: 'Deposit received', done: true },
          { label: 'Material ordered', done: true },
          { label: 'Schedule confirmed', done: false },
        ],
      },
      {
        id: 'WIQ-099',
        name: 'Ford Transit Fleet Graphics',
        vehicle: '2025 Ford Transit (x5) — White',
        client: 'GreenLeaf Landscaping',
        value: 14500,
        date: '2026-03-20',
        priority: 'medium',
        tags: ['fleet', 'commercial', 'partial'],
        team: [
          { initials: 'JD', color: '#2563eb' },
          { initials: 'AM', color: '#059669' },
        ],
      },
    ],
  },
  {
    id: 'design',
    title: 'Design',
    color: '#d97706',
    cards: [
      {
        id: 'WIQ-094',
        name: 'Porsche 911 PPF + Accent Wrap',
        vehicle: '2024 Porsche 911 GT3 — Guards Red',
        client: 'Velocity Auto Club',
        value: 8200,
        date: '2026-03-10',
        priority: 'high',
        tags: ['partial', 'design'],
        team: [{ initials: 'LN', color: '#e11d48' }],
        progress: 65,
        tasks: [
          { label: 'Template created', done: true },
          { label: 'Client mockup approval', done: true },
          { label: 'Print file prep', done: false },
          { label: 'Color proof sent', done: false },
        ],
      },
      {
        id: 'WIQ-095',
        name: 'Chevy Silverado Partial Wrap',
        vehicle: '2024 Chevrolet Silverado — Black',
        client: 'Summit Electric Co.',
        value: 3200,
        date: '2026-03-14',
        priority: 'low',
        tags: ['partial', 'commercial', 'design'],
        team: [{ initials: 'LN', color: '#e11d48' }],
        progress: 30,
      },
      {
        id: 'WIQ-096',
        name: 'Rivian R1T Adventure Wrap',
        vehicle: '2025 Rivian R1T — Matte Forest Green',
        client: 'TrailBound Outdoors',
        value: 5800,
        date: '2026-03-16',
        priority: 'medium',
        tags: ['full-wrap', 'design'],
        team: [
          { initials: 'LN', color: '#e11d48' },
          { initials: 'KR', color: '#7c3aed' },
        ],
        progress: 10,
      },
    ],
  },
  {
    id: 'production',
    title: 'Production',
    color: '#059669',
    cards: [
      {
        id: 'WIQ-089',
        name: 'Audi RS6 Satin Wrap',
        vehicle: '2024 Audi RS6 Avant — Satin Nardo Grey',
        client: 'Prestige Motors',
        value: 6100,
        date: '2026-03-08',
        priority: 'high',
        tags: ['full-wrap', 'print'],
        team: [
          { initials: 'AM', color: '#059669' },
          { initials: 'JD', color: '#2563eb' },
        ],
        progress: 80,
        tasks: [
          { label: 'Material printed', done: true },
          { label: 'Laminated', done: true },
          { label: 'Cut & weeded', done: false },
          { label: 'QC check', done: false },
        ],
      },
      {
        id: 'WIQ-090',
        name: 'Toyota Tacoma Camo Wrap',
        vehicle: '2025 Toyota Tacoma TRD — Army Green Camo',
        client: 'Mike Chen',
        value: 4800,
        date: '2026-03-09',
        priority: 'medium',
        tags: ['full-wrap', 'print'],
        team: [{ initials: 'AM', color: '#059669' }],
        progress: 50,
      },
    ],
  },
  {
    id: 'install',
    title: 'Install',
    color: '#e11d48',
    cards: [
      {
        id: 'WIQ-085',
        name: 'Lamborghini Urus Chrome Delete',
        vehicle: '2024 Lamborghini Urus — Gloss Black Trim',
        client: 'Elite Auto Spa',
        value: 2800,
        date: '2026-03-07',
        priority: 'high',
        tags: ['partial', 'install'],
        team: [
          { initials: 'JD', color: '#2563eb' },
          { initials: 'KR', color: '#7c3aed' },
        ],
        progress: 90,
        tasks: [
          { label: 'Surface prep', done: true },
          { label: 'Panel wrapping', done: true },
          { label: 'Detail trim', done: false },
          { label: 'Final QC', done: false },
        ],
      },
    ],
  },
  {
    id: 'complete',
    title: 'Complete',
    color: '#6b7280',
    cards: [
      {
        id: 'WIQ-080',
        name: 'Range Rover Sport Full Wrap',
        vehicle: '2024 Range Rover Sport — Matte Military Green',
        client: 'David Kim',
        value: 7200,
        date: '2026-03-01',
        priority: 'low',
        tags: ['full-wrap'],
        team: [
          { initials: 'JD', color: '#2563eb' },
          { initials: 'AM', color: '#059669' },
          { initials: 'KR', color: '#7c3aed' },
        ],
      },
      {
        id: 'WIQ-081',
        name: 'Honda Civic Type R Accents',
        vehicle: '2025 Honda Civic Type R — Carbon Fiber Accents',
        client: 'Sarah Walsh',
        value: 1800,
        date: '2026-03-03',
        priority: 'low',
        tags: ['partial'],
        team: [{ initials: 'KR', color: '#7c3aed' }],
      },
    ],
  },
];

export const dashboardStats = [
  { label: 'Active Jobs', value: '12', change: '+3 this week' },
  { label: 'Pipeline Value', value: '$64,900', change: '+$8.2k' },
  { label: 'Avg Completion', value: '6.2 days', change: '-0.5 days' },
  { label: 'On-Time Rate', value: '94%', change: '+2%' },
];
